# Generated by Django 5.0.6 on 2024-06-24 09:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[core.validators.validate_file_type]),
        ),
    ]
