# Generated by Django 5.0.6 on 2024-06-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_uploadfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
